### PR TITLE
Fix 27

### LINKED ISSUE #27: DaysPassed overflows an array if the player has put more than 2048 items in a level
Popo McTroll reports:
> I'm not sure if this is the right place to post about a bug, but twice so far I've had level 9 Rangers try to go downstairs to the 6th floor but the game crashes every time I try it. I suspect it might be because I hoard a lot of arrows and I rest a lot, so the game gets overloaded, so to speak. It also sometimes crashes when I try to rest.

And adds on inquiry:
> I was using version 0.6.9Y19.
> Executable just exits.

Debugging against the old debug binaries of 0.6.9Y19 is problematic as the source files do not match my tag. We should preserve the source code and binaries together as a build artifact and just make it a one step debugging process. It is however close enough to work out what is wrong.

image

Popo has accrued 3665 objects in the level he is leaving. The code crashes around 2071.

[SaveGame-0.6.9Y19.zip](https://github.com/user-attachments/files/16706740/SaveGame-0.6.9Y19.zip)

### LINKED ISSUE #30: isspace and family assert on negative values
Reproduction:

1. Debug Incursion.
2. Create a new character. Select the first option out of every choice until in game.
3. Press '<' to ascend.
4. Enter the inn, 'i'.
5. Press 'd' to descend.
6. Press escape then quit the game.
7. Observe that a literal finally hits `isspace`.

````
 	Incursion.exe!_chvalidator(int c, int mask) Line 36	C++
 	Incursion.exe!fast_check_initial_locale(const int c, const int mask) Line 26	C++
 	Incursion.exe!fast_check_current_locale(const int c, const int mask) Line 33	C++
>	Incursion.exe!isspace(int c) Line 148	C++
 	Incursion.exe!String::Trim() Line 311	C++
 	Incursion.exe!Detable(const char * _s, char mode) Line 1271	C++
 	Incursion.exe!TextTerm::CreateCharDump(String & str) Line 1316	C++
 	Incursion.exe!TextTerm::DumpCharacter(String & filebase) Line 1394	C++
 	Incursion.exe!Player::Gravestone() Line 2270	C++
 	Incursion.exe!Game::Play() Line 423	C++
 	Incursion.exe!Game::StartMenu() Line 2147	C++
 	Incursion.exe!main(int argc, char * * argv) Line 377	C++
 	[External Code]	
```

### PR DESCRIPTION
**Pull request by HexDecimal**
Fixed-size stack replaced by std::vector preventing an overflow. Fixes #27

Also encountered assertion errors related to my PR #21 while testing. I've added a more complete solution. Closes #30 

I need to test if the vector size is off-by-one. I'll put down a breakpoint and play until it's triggered.

### CODE REVIEW

**Comment by rmtew** [comment]
Was `tokens.cpp` manually edited or regenerated via build action?

**Comment by HexDecimal** [comment]
I manually edited it. I'm not sure of the steps to reregenerate it.

**Comment by rmtew** [comment]
Change to debug configuration. Right click on `Language files/tokens.lex` look at "Custom Build Tool". Repeat for `grammar.acc`. These should be run when "lib_incursion" is built. Sometimes they do, sometimes they don't. Delete the `src/tokens.cpp` on disk to make sure it doesn't compile unless you get it working.

**Comment by HexDecimal** [comment]
I've verified the vector is the correct size.

**Comment by HexDecimal** [comment]
Could not find "Custom Build Tool" in the solution explorer for `Language files/tokens.lex`.

I manually deleted `tokens.cpp` and it was recreated by the solution.

**Comment by rmtew** [comment]
image

**Comment by HexDecimal** [comment]
These files can be verified by the CI if they're reproducible. `tokens.cpp` is, but `yygram.*` isn't unless the paths are normalized.

**Pull request merged**
